const CONST = {
  TOAST_TYPES: {
    ERROR: 'error',
    WARN: 'warn',
    SUCCESS: 'success',
    INFO: 'info',
  },
  SAUDI_CODE: '+966',
  USER_TYPE: {
    CUSTOMER: 0,
    WORKER: 1,
  },
  COUNTRY_TYPE: {
    IN_COUNTRY: 0,
    OTHER_COUNTRY: 1,
  },
  BAND_STATUS: {
    ACTIVE: 1,
    IN_ACTIVE: 2,
  },
  RESPONSE_TYPE: {
    SUCCESS: 1,
    FAILURE: 2,
  },
  CARD_PAGE_TYPE: {
    CREATE: 1,
    UPDATE: 2,
  },
  STATUS_CODE: {
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    NOT_FOUND: 404,
  },
  CARD_TYPE: {
    REVOLUT_CARD: 0,
    IBAN: 1,
  },
  CUSTOMER_CARE_ISSUE: [
    { id: 1, menuLabel: 'Payment' },
    { id: 2, menuLabel: 'Wristband' },
    { id: 3, menuLabel: 'Account' },
    { id: 4, menuLabel: 'QR Code' },
    { id: 5, menuLabel: 'Tip Amount' },
    { id: 6, menuLabel: 'Commission' },
    { id: 7, menuLabel: 'Technical' },
    { id: 8, menuLabel: 'Other' },
  ],

  //Adjust
  ADJUST_TYPE_WORKER: {
    WorkerKYCMobile: 1,
    WorkerKYCId: 2,
    WorkerKYCDob: 3,
    WorkerEditProfilePicture: 4,
    WorkerOTP: 5,
    WristbandScan: 6,
    QRCodeScan: 7,
    ReceiveTipCard: 8,
    ReceiveTipApplePay: 9,
    ReceiveTipWebpage: 10,
    ReceiveTipInApp: 11,
    WristbandPeering: 12,
    OrderNewWristband: 13,
    SplitCreation: 14,
    SplitUpdate: 15,
    WorkerLogin: 16,
    ResetPassword: 17,
    WorkerLogout: 18,
  },
  //ADJUST_APP_TOKEN: 'dr1dzedi3668',
  ADJUST_EVENT_WORKER: {
    WorkerKYCMobile_Event: 'c3mfby',
    WorkerKYCId_Event: 'q8txt8',
    WorkerKYCDob_Event: 'vcrzmh',
    WorkerEditProfilePicture_Event: 'vwfw3r',
    WorkerOTP_Event: 'woqzg7',
    WristbandScan_Event: 'oobn7q',
    QRCodeScan_Event: 'nap44z',
    ReceiveTipCard_Event: '9td7ce',
    ReceiveTipApplePay_Event: 'wnzoa0',
    ReceiveTipWebpage_Event: '2fre9t',
    ReceiveTipInApp_Event: 'a7oh51',
    WristbandPeering_Event: 'nkfy24',
    OrderNewWristband_Event: '4ka05r',
    SplitCreation_Event: 'nmn2vy',
    SplitUpdate_Event: 'vh1cev',
    WorkerLogin_Event: '616h1p',
    ResetPassword_Event: 'qaqxwt',
    WorkerLogout_Event: 'lhteao',
  },
  ADJUST_TYPE_CUSTOMER: {
    Registration: 19,
    CustomerLogin: 20,
    CustomerEditProfilePicture: 21,
    WristbandScan: 22,
    PayTipCard: 23,
    PayTipApplePay: 24,
    PayTipRevolut: 25,
    ScanQRCode: 26,
    RateWorker: 27,
    CardSaving: 28,
    PayThroughWebpage: 29,
    PayInApp: 30,
    CustomerLogout: 31,
  },
  ADJUST_EVENT_CUSTOMER: {
    CustomerRegistration_Event: 'towkri',
    CustomerLogin_Event: 'ih7qd8',
    CustomerEditProfilePicture_Event: '31ysyu',
    WristbandScan_Event: 'oobn7q',
    PayTipCard_Event: 'w6kkwc',
    PayTipApplePay_Event: '49x4b1',
    PayTipRevolut_Event: 'qieqvz',
    ScanQRCode_Event: '21wkcm',
    RateWorker_Event: 'qtwv5s',
    CardSaving_Event: 'bhmlyc',
    PayThroughWebpage_Event: '20iw7g',
    PayInapp_Event: 'l6u9vs',
    CustomerLogout_Event: 'cqi40a',
  },
};

export default CONST;
